import { useState } from 'react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Users, CheckCircle, XCircle, MessageSquare, Loader2 } from 'lucide-react';
import { api, getActiveAuditId } from '../lib/api';

const mockQueue = [
  { id: 'REQ-8891', dept: 'Engineering', impact: '$1.2M', gapReduction: '14.2% → 2.1%', date: 'Just now' },
  { id: 'REQ-8890', dept: 'Product Design', impact: '$340k', gapReduction: '8.4% → 1.5%', date: '2 hrs ago' },
  { id: 'REQ-8888', dept: 'Marketing', impact: '$890k', gapReduction: '11.0% → 1.8%', date: '1 day ago' },
];

export default function HitlQueuePage() {
  const [selected, setSelected] = useState(mockQueue[0]);
  const [submitting, setSubmitting] = useState(false);
  const [decisionMsg, setDecisionMsg] = useState("");

  const handleDecision = async (decision: string) => {
    setSubmitting(true);
    setDecisionMsg("");
    try {
      const auditId = getActiveAuditId() || selected.id;
      const res = await api.submitHitlDecision(auditId, decision);
      setDecisionMsg(res.message);
    } catch (e) {
      console.error(e);
      setDecisionMsg("Failed to submit decision.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="h-full flex flex-col space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-white mb-2">Human-in-the-Loop Review Queue</h2>
        <p className="text-gray-400">Mandatory executive review for all proposed equity adjustments.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 min-h-0">
        {/* Queue List */}
        <Card className="col-span-1 border-white/5 p-4 flex flex-col overflow-hidden">
          <div className="flex items-center space-x-2 mb-4 px-2">
            <Users className="w-5 h-5 text-amber-500" />
            <h3 className="text-sm font-medium text-white">Pending Reviews (3)</h3>
          </div>
          <div className="space-y-2 overflow-y-auto flex-1 pr-2">
            {mockQueue.map(req => (
              <div 
                key={req.id}
                onClick={() => { setSelected(req); setDecisionMsg(""); }}
                className={`p-3 rounded-lg border cursor-pointer transition-colors ${
                  selected.id === req.id 
                    ? 'bg-white/10 border-white/20' 
                    : 'bg-charcoal-900 border-white/5 hover:border-white/10'
                }`}
              >
                <div className="flex justify-between items-start mb-2">
                  <span className="text-sm font-medium text-white">{req.id}</span>
                  <span className="text-xs text-gray-500">{req.date}</span>
                </div>
                <p className="text-sm text-gray-400">{req.dept}</p>
                <div className="mt-2 flex space-x-3 text-xs">
                  <span className="text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded">Impact: {req.impact}</span>
                </div>
              </div>
            ))}
          </div>
        </Card>

        {/* Detail View */}
        <Card className="lg:col-span-2 border-white/5 flex flex-col overflow-hidden">
          <div className="flex-1 overflow-y-auto pr-2 space-y-6">
            <div className="flex justify-between items-start border-b border-white/10 pb-4">
              <div>
                <h3 className="text-xl font-medium text-white mb-1">{selected.id} — {selected.dept} Equity Adjustment</h3>
                <p className="text-sm text-gray-400">Generated by Equity Framework Agent</p>
              </div>
              <span className="bg-amber-500/10 border border-amber-500/20 text-amber-400 text-sm px-3 py-1 rounded-full">
                Needs Approval
              </span>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-charcoal-900 rounded-lg border border-white/5">
                <p className="text-sm text-gray-400 mb-1">Financial Impact</p>
                <p className="text-2xl font-bold text-white">{selected.impact}</p>
              </div>
              <div className="p-4 bg-charcoal-900 rounded-lg border border-emerald-500/30">
                <p className="text-sm text-gray-400 mb-1">Projected Gap Reduction</p>
                <p className="text-2xl font-bold text-emerald-500">{selected.gapReduction}</p>
              </div>
            </div>

            <div>
              <h4 className="text-sm font-medium text-white mb-3">Agent Evidence & Privacy Guarantees</h4>
              <div className="space-y-3">
                <div className="p-3 bg-white/5 rounded border border-white/5 flex items-start space-x-3">
                  <CheckCircle className="w-5 h-5 text-emerald-500 mt-0.5 flex-shrink-0" />
                  <p className="text-sm text-gray-300">Swarm consensus reached. Counterfactual analysis confirmed structural penalty unrelated to performance metrics.</p>
                </div>
                <div className="p-3 bg-white/5 rounded border border-white/5 flex items-start space-x-3">
                  <CheckCircle className="w-5 h-5 text-teal-500 mt-0.5 flex-shrink-0" />
                  <p className="text-sm text-gray-300">Differential Privacy bounds maintained (ε=0.1). No PII exposed in reasoning traces.</p>
                </div>
              </div>
            </div>

            <div>
              <h4 className="text-sm font-medium text-white mb-3">Executive Comment</h4>
              <textarea 
                className="w-full h-24 bg-charcoal-900 border border-white/10 rounded-lg p-3 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-emerald-500/50"
                placeholder="Add compliance notes or rationale for decision..."
              />
            </div>
            
            {decisionMsg && (
              <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded">
                {decisionMsg}
              </div>
            )}
          </div>

          <div className="pt-4 border-t border-white/10 flex justify-end space-x-3 mt-4">
            <Button variant="ghost" disabled={submitting}>
              <MessageSquare className="w-4 h-4 mr-2" />
              Request Agent Changes
            </Button>
            <Button variant="danger" disabled={submitting} onClick={() => handleDecision("reject")}>
              {submitting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <XCircle className="w-4 h-4 mr-2" />}
              Reject
            </Button>
            <Button variant="primary" disabled={submitting} onClick={() => handleDecision("approve")}>
              {submitting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <CheckCircle className="w-4 h-4 mr-2" />}
              Approve Adjustments
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
}
